grails-app/domain/com/mice/Authority.groovy
package com.mice

class Authority {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails-app/domain/com/mice/Node.groovy
package com.mice

class Node {
	
	String label
	Double data
	Date dateCreated
	Date lastUpdated

    static constraints = {
    label blank:false, unique:true
	data nullable: true
	}
}

grails-app/domain/com/mice/Person.groovy
package com.mice

class Person {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Authority> getAuthorities() {
		PersonAuthority.findAllByPerson(this).collect { it.authority } as Set
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}
}

grails-app/domain/com/mice/PersonAuthority.groovy
package com.mice

import org.apache.commons.lang.builder.HashCodeBuilder

class PersonAuthority implements Serializable {

	private static final long serialVersionUID = 1

	Person person
	Authority authority

	boolean equals(other) {
		if (!(other instanceof PersonAuthority)) {
			return false
		}

		other.person?.id == person?.id &&
			other.authority?.id == authority?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (person) builder.append(person.id)
		if (authority) builder.append(authority.id)
		builder.toHashCode()
	}

	static PersonAuthority get(long personId, long authorityId) {
		PersonAuthority.where {
			person == Person.load(personId) &&
			authority == Authority.load(authorityId)
		}.get()
	}

	static PersonAuthority create(Person person, Authority authority, boolean flush = false) {
		new PersonAuthority(person: person, authority: authority).save(flush: flush, insert: true)
	}

	static boolean remove(Person u, Authority r, boolean flush = false) {

		int rowCount = PersonAuthority.where {
			person == Person.load(u.id) &&
			authority == Authority.load(r.id)
		}.deleteAll()

		rowCount > 0
	}

	static void removeAll(Person u) {
		PersonAuthority.where {
			person == Person.load(u.id)
		}.deleteAll()
	}

	static void removeAll(Authority r) {
		PersonAuthority.where {
			authority == Authority.load(r.id)
		}.deleteAll()
	}

	static mapping = {
		id composite: ['authority', 'person']
		version false
	}
}

grails-app/domain/com/mice/Requestmap.groovy
package com.mice

import org.springframework.http.HttpMethod

class Requestmap {

	String url
	String configAttribute
	HttpMethod httpMethod

	static mapping = {
		cache true
	}

	static constraints = {
		url blank: false, unique: 'httpMethod'
		configAttribute blank: false
		httpMethod nullable: true
	}
}

grails-app/controllers/com/mice/HomeController.groovy
package com.mice
import grails.plugin.springsecurity.annotation.Secured


class HomeController {

@Secured(['ROLE_ADMIN'])
	def setting(){
	
	
	}
@Secured(['ROLE_ADMIN','ROLE_USER'])
    def index() { }
	
	@Secured(['ROLE_ADMIN','ROLE_USER'])
    def about() { }
	
}

grails-app/controllers/com/mice/MapController.groovy
package com.mice
import grails.plugin.springsecurity.annotation.Secured

class MapController {

@Secured(['ROLE_ADMIN'])
    def index() {

	}
	@Secured(['ROLE_ADMIN'])
	def gis() {
	
	}
}

grails-app/controllers/com/mice/NodeChartController.groovy
package com.mice
import java.lang.String
import java.io.InputStream
import java.io.File
import groovy.util.XmlParser
import groovy.xml.StreamingMarkupBuilder
import groovy.sql.Sql
import grails.plugin.springsecurity.annotation.Secured

class NodeChartController {

@Secured(['ROLE_ADMIN','ROLE_USER'])
    def index () { 
		
	}
	def temperature = {
	
	}
	@Secured(['ROLE_ADMIN','ROLE_USER'])
	def realtime () {
	
	
	
	
	}
	
	
	def dataSource // the Spring-Bean "dataSource" is auto-injected
	def dbToXMLService
@Secured(['ROLE_ADMIN','ROLE_USER'])
    def list () {
      
		
		
	}
	
@Secured(['ROLE_ADMIN','ROLE_USER'])
	def test() {

	}

}

grails-app/controllers/com/mice/NodeController.groovy
package com.mice
import grails.plugin.springsecurity.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
@Secured(['ROLE_ADMIN','ROLE_USER'])
@Transactional(readOnly = true)
class NodeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Node.list(params), model:[nodeInstanceCount: Node.count()]
    }

    def show(Node nodeInstance) {
        respond nodeInstance
    }

    def create() {
        respond new Node(params)
    }

    @Transactional
    def save(Node nodeInstance) {
        if (nodeInstance == null) {
            notFound()
            return
        }

        if (nodeInstance.hasErrors()) {
            respond nodeInstance.errors, view:'create'
            return
        }

        nodeInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'nodeInstance.label', default: 'Node'), nodeInstance.id])
                redirect nodeInstance
            }
            '*' { respond nodeInstance, [status: CREATED] }
        }
    }

    def edit(Node nodeInstance) {
        respond nodeInstance
    }

    @Transactional
    def update(Node nodeInstance) {
        if (nodeInstance == null) {
            notFound()
            return
        }

        if (nodeInstance.hasErrors()) {
            respond nodeInstance.errors, view:'edit'
            return
        }

        nodeInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Node.label', default: 'Node'), nodeInstance.id])
                redirect nodeInstance
            }
            '*'{ respond nodeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Node nodeInstance) {

        if (nodeInstance == null) {
            notFound()
            return
        }

        nodeInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Node.label', default: 'Node'), nodeInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'nodeInstance.label', default: 'Node'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/home/about.gsp
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'style.css')}" type="text/css">
	<title>Hello</title>
	<style type='text/css' media='screen'>
	img {
	max-width: 100%;
	height: auto;
	}
	@media \0screen {
	  img { 
		width: auto; /* for ie 8 */
	  }
	}
	@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700);
	
	</style>
</head>
<body>

 
 
 <div id="container" style="background-color:#0066cc " width="100%">
<div id="header" style="background-color:#0066cc;font-family:verdana;text-align:left;padding-top:5px;color:white;">
<div style="position:absolute;right:20px;padding:20px;height:75px; width:150px" align="center" method="post" action="">
				<sec:ifLoggedIn>
				Welcome Back! <b><sec:username/></b> <br/>
				<g:link controller='logout'>Logout</g:link>
				</sec:ifLoggedIn>
				<sec:ifNotLoggedIn>
				<g:link controller="login" action="auth">Login</g:link>
				</sec:ifNotLoggedIn>				
</div>
<g:img dir="images" file="combine.png" width="90px" height="90px" style="padding-left:20px; padding-top:10px; position:absolute;left:20px"/>
<h1 align="center;" style="padding-left:140px;">WiTMon</h1>
<p style="letter-spacing:8px;font-size:20px;padding-left:140px;">Wireless Distribution Transformer Monitoring System</p>
<div id='cssmenu'>
<ul>
   <li><a href="/mice/"><g:img dir="images" file="home.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Home</span></a></li>
   <li><a href="/mice/nodeChart/index"><g:img dir="images" file="graph.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Visualization</span></a></li>
   <li><a href="/mice/map/index"><g:img dir="images" file="map.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Location</span></a></li>
  <li><a href="/mice/user"  target="_blank" ><g:img dir="images" file="set.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Settings</span></a></li>
   <li class='active'><a href="/mice/home/about"><g:img dir="images" file="aboutus.png" height="15px" width="15 px" /><span style="font-size:15px">&nbsp <span>About Us</span></a></li>
</ul>
</div>

<div id="content" style="button:100%; height:100%;">
<table style="width:100%; height:500px" >
<tr >
	<td><g:img dir="images" file="MICE.jpg"/></td>
<td width="652px" style="padding:20px">
<h2 style="font-family: courier">


<h3>Team Mice</h3>

<h4>We are the 5th year Computer Engineering Students from Mindanao State University- Iligan Institute of Technology(MSU-IIT)</h4>
<br/>
<br/>

<br/>

 Members: 

<ol>
<li>Kister Genesis M. Jimenez (Adviser)</li>
<li>Kim Chesed F. Paler</li>
<li>Jimmy E. Unilongo Jr.</li>
<li>Romarie E. Yuag</li>
</ol>

</h2>
</td>
</tr>
</table>
</div>

<div id="footer" style="background-color:#FFA500;position:fixed; clear:both;text-align:center;width:100%;bottom:0px">
&copy 2014 MICE</div>


</div>
</div>
 
 
 
 
 
</body>

</html>

grails-app/views/home/dtree.gsp
<html>
<head>
	<title>Hello</title>
</head>
<body>
<h1>Hi</h1>

</body>

</html>

grails-app/views/home/index.gsp
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'style.css')}" type="text/css">
	<title>Welcome to WiTMon</title>
	<style type='text/css' media='screen'>
	img {
	max-width: 100%;
	height: auto;
	}
	@media \0screen {
	  img { 
		width: auto; /* for ie 8 */
	  }
	}
	@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700);
	
	</style>
</head>
<body>

 
 
 <div id="container" width="100%">
<div id="header"   style="background-color:#0066cc;font-family:verdana;text-align:left;padding-top:5px;color:white;">
<div style="position:absolute;right:20px;padding:20px;height:75px; width:150px" align="center" method="post" action="">
				<sec:ifLoggedIn>
				Welcome Back! <b><sec:username/></b> <br/>
				<g:link controller='logout'>Logout</g:link>
				</sec:ifLoggedIn>
				<sec:ifNotLoggedIn>
				<g:link controller="login" action="auth">Login</g:link>
				</sec:ifNotLoggedIn>				
</div>
<g:img dir="images" file="combine.png" width="90px" height="90px" style="padding-left:20px; padding-top:10px; position:absolute;left:20px"/>
<h1 align="center;" style="padding-left:140px;">WiTMon</h1>
<p style="letter-spacing:8px;font-size:20px;padding-left:140px;">Wireless Distribution Transformer Monitoring System</p>
<div id='cssmenu'>
<ul>
   <li class='active'><a href="/mice/"><g:img dir="images" file="home.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Home</span></a></li>
   <li><a href="/mice/nodeChart/index"><g:img dir="images" file="graph.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Visualization</span></a></li>
   <li><a href="/mice/map/index"><g:img dir="images" file="map.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Location</span></a></li>
   <li><a href="/mice/user"  target="_blank" ><g:img dir="images" file="set.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Settings</span></a></li>
   <li class='last'><a href="/mice/home/about"><g:img dir="images" file="aboutus.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>About Us</span></a></li>
</ul>
</div>
<div id="content" style="button:100%; height:500px;">



<div id="menu" align="center" style="background-color:#FFD700;height:400px;width:25%;float:left;padding-top:70px;">

<g:img dir="images" file="network-icon.png"/><br>
<p style="color:black">WiTMon uses scalable wireless sensor network and reliable data forwarding protocol to improve data delivery and acquisition.</p>
</div>

<div id="content" align="center" style="background-color:#ff66ff;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="power-management-icon.png"/>
<p style="color:black">It can help lower maintenance cost, extend life of the transformer and avoid unplanned failures.</p>
</div>

<div id="content" align="center" style="background-color:#33ff33;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="monitor-icon.png"/>
<p style="color:black">This provides the information and graphical presentation of the performance of the distribution transformer.</p>
</div>

<div id="content" align="center" style="background-color:#cc99ff;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="energy-icon.png"/>
<p style="color:black">It does not only help save money but also we can save more energy.</p>
</div>


</div>

<div id="footer" style="background-color:#FFA500;position:fixed; clear:both;text-align:center;width:100%;bottom:0px">
&copy 2014 MICE</div>

</div>
</div>
 
 
 
 
 
</body>

</html>

grails-app/views/home/setting.gsp
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'style.css')}" type="text/css">
	<title>Hello</title>
	<style type='text/css' media='screen'>
	img {
	max-width: 100%;
	height: auto;
	}
	@media \0screen {
	  img { 
		width: auto; /* for ie 8 */
	  }
	}
	@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700);
	
	</style>
</head>
<body>

 
 
 <div ic="container" width="100%">
<div id="header"   style="background-color:#0066cc;font-family:verdana;text-align:left;padding-top:5px;color:white;">
<div style="position:absolute;right:20px;padding:20px;height:75px; width:150px" align="center" method="post" action="">
				<sec:ifLoggedIn>
				Welcome Back! <b><sec:username/></b> <br/>
				<g:link controller='logout'>Logout</g:link>
				</sec:ifLoggedIn>
				<sec:ifNotLoggedIn>
				<g:link controller="login" action="auth">Login</g:link>
				</sec:ifNotLoggedIn>				
</div>
<g:img dir="images" file="combine.png" width="90px" height="90px" style="padding-left:20px; padding-top:10px; position:absolute;left:20px"/>
<h1 align="center;" style="padding-left:140px;">WiTMon</h1>
<p style="letter-spacing:8px;font-size:20px;padding-left:140px;">Wireless Distribution Transformer Monitoring System</p>
<div id='cssmenu'>
<ul>
   <li><a href="/mice/"><g:img dir="images" file="home.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Home</span></a></li>
   <li><a href="/mice/nodeChart/index"><g:img dir="images" file="graph.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Visualization</span></a></li>
   <li><a href="/mice/map/index"><g:img dir="images" file="map.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Location</span></a></li>
   <li class='active'><a href="/mice/home/setting"><g:img dir="images" file="set.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Settings</span></a></li>
 <li class='last'><a href="/mice/home/about"><g:img dir="images" file="aboutus.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>About Us</span></a></li>
   </ul>
</div>
<div id="content" style="button:100%; height:500px;">
<g:link controller="user" action="create" target="_blank"><g:img dir="images" file="add.png" height="50px" width="50px" /><span style="font-size:15px">Manage Users</span></g:link>
</div>

<div id="footer" style="background-color:#FFA500;position:fixed; clear:both;text-align:center;width:100%;bottom:0px">
&copy 2014 MICE</div>

</div>
</div>
 
 
 
 
 
</body>

</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'style.css')}" type="text/css">
	<title>Hello</title>
	<style type='text/css' media='screen'>
	img {
	max-width: 100%;
	height: auto;
	}
	@media \0screen {
	  img { 
		width: auto; /* for ie 8 */
	  }
	}
	@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700);
	
	</style>
</head>
<body>

 
 
 <div ic="container" width="100%">
<div id="header"   style="background-color:#0066cc;font-family:verdana;text-align:left;padding-top:5px;color:white;">
<div style="position:absolute;right:20px;padding:20px;height:75px; width:150px" align="center" method="post" action="">
				<sec:ifLoggedIn>
				Welcome Back! <b><sec:username/></b> <br/>
				<g:link controller='logout'>Logout</g:link>
				</sec:ifLoggedIn>
				<sec:ifNotLoggedIn>
				<g:link controller="login" action="auth">Login</g:link>
				</sec:ifNotLoggedIn>				
</div>
<g:img dir="images" file="combine.png" width="90px" height="90px" style="padding-left:20px; padding-top:10px; position:absolute;left:20px"/>
<h1 align="center;" style="padding-left:140px;">WiTMon</h1>
<p style="letter-spacing:8px;font-size:20px;padding-left:140px;">Wireless Distribution Transformer Monitoring System</p>
<div id='cssmenu'>
<ul>
   <li class='active'><a href="/mice/"><g:img dir="images" file="home.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Home</span></a></li>
   <li><a href="/mice/nodeChart/realtime"><g:img dir="images" file="graph.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp Visualization</span></a></li>
   <li><a href="/mice/map/index"><g:img dir="images" file="map.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Location</span></a></li>
   <li class='last'><a href="/mice/home/setting"><g:img dir="images" file="graph.png" height="15px" width="15px" /><span style="font-size:15px">&nbsp <span>Settings</span></a></li>
</ul>
</div>
<div id="content" height="100px">
<br/>
</div>

<div id="footer" style="background-color:#FFA500;clear:both;text-align:center;bottom:10px">
&copy 2014 MICE</div>

</div>
</div>
 
 
 
 
 
</body>

</html>

grails-app/views/login/auth.gsp
<!DOCTYPE html>
<html>
<head>

	<title>Welcone to WiTMon</title>
<style type='text/css' media='screen'>
	img {
		max-width: 100%;
		height: auto;
	}
	@media \0screen {
	  img { 
		width: auto; /* for ie 8 */
	  }
	}
	</style>
</head>
<body>
<div ic="container" width="100%">
<div id="header"   style="background-color:#0066cc;font-family:verdana;text-align:left;padding-top:5px;color:white;">
<sec:ifLoggedIn>
				Welcome Back! <b><sec:username/></b> <g:link controller='logout'>Logout</g:link>
				</sec:ifLoggedIn>		
				
				<sec:ifNotLoggedIn>
				<form action='${postUrl}' method='POST' id='loginForm' class='cssform' autocomplete='off' style="position:absolute;right:20px; " align="center">
			<br/>
				<input type='text' class='text_' name='j_username' placeholder="Username" id='username'/>
			<br/>	
				<input type='password' class='text_' name='j_password'  placeholder="Password" id='password'/>
			<br/>
			<p id="remember_me_holder">
				<input type='checkbox' class='chk' name='${rememberMeParameter}' id='remember_me' <g:if test='${hasCookie}'>checked='checked'</g:if>/>
				<input type='submit' id="submit" value='${message(code: "springSecurity.login.button")}'/>
		<br/>
		</form>
				</sec:ifNotLoggedIn>


<g:img dir="images" file="combine.png" width="90px" height="90px" style="padding-left:20px; padding-top:10px; position:absolute;left:20px"/>
<h1 align="center;" style="padding-left:140px;">WiTMon</h1>
<p style="letter-spacing:8px;font-size:20px;padding-left:140px;">Wireless Distribution Transformer Monitoring System</p>
<div id="menu" align="center" style="background-color:#FFD700;height:400px;width:25%;float:left;padding-top:70px;">

<g:img dir="images" file="network-icon.png"/><br>
<p style="color:black">WiTMon uses scalable wireless sensor network and reliable data forwarding protocol to improve data delivery and acquisition.</p>
</div>

<div id="content" align="center" style="background-color:#ff66ff;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="power-management-icon.png"/>
<p style="color:black">It can help lower maintenance cost, extend life of the transformer and avoid unplanned failures.</p>
</div>

<div id="content" align="center" style="background-color:#33ff33;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="monitor-icon.png"/>
<p style="color:black">This provides the information and graphical presentation of the performance of the distribution transformer.</p>
</div>

<div id="content" align="center" style="background-color:#cc99ff;height:400px;width:25%;float:left;padding-top:70px;">
<g:img dir="images" file="energy-icon.png"/>
<p style="color:black">It does not only help save money but also we can save more energy.</p>
</div>
<div id="content" style="button:100%; height:700px;">
</div>
<div id="footer" style="background-color:#FFA500;position:fixed; clear:both;text-align:center;width:100%;bottom:0px">
&copy 2014 MICE</div>

</div>
</div>
</body>

</html>

grails-app/views/login/denied.gsp
<head>
<meta name='layout' content='main' />
<title><g:message code="springSecurity.denied.title" /></title>
</head>

<body>
<div class='body'>
	<div class='errors'><g:message code="springSecurity.denied.message" /></div>
</div>
</body>

grails-app/views/map/gis.gsp
<!DOCTYPE html>
<html>
<head>
	
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'style.css')}" type="text/css">
	<title>WiTmon</title>
	
    <script src="http://openlayers.org/dev/OpenLayers.js"></script>
     <script type="text/javascript">
            var lat=8.24118;
            var lon=124.24520;
            var zoom=18;
            var map;
 
            function init(){
                map = new OpenLayers.Map ("map");
 
                map.addControl(new OpenLayers.Control.LayerSwitcher());
                
                map.addLayer(new OpenLayers.Layer.OSM()); //OSM base map
 
                var lonLat = new OpenLayers.LonLat(lon, lat).transform(new OpenLayers.Projection("EPSG:4326"), new OpenLayers.Projection("EPSG:900913"));
 
                map.setCenter (lonLat, zoom);

                //Initialise the vector layer using OpenLayers.Format.OSM
                var layer = new OpenLayers.Layer.Vector("Polygon", {
                    strategies: [new OpenLayers.Strategy.Fixed()],
                    protocol: new OpenLayers.Protocol.HTTP({
                        url: "${resource(dir: 'OUTPUT', file: 'map.osm')}",   //<-- relative or absolute URL to your .osm file
                        format: new OpenLayers.Format.OSM()
                    }),
                    projection: new OpenLayers.Projection("EPSG:4326")
                });
 
                map.addLayers([layer]);
            }
        </script>
</head>
<body onload="init()">
<div id="map"></div>
  
 
 
</body>

</html>

grails-app/views/node/_form.gsp
<%@ page import="com.mice.Node" %>



<div class="fieldcontain ${hasErrors(bean: nodeInstance, field: 'label', 'error')} required">
	<label for="label">
		<g:message code="node.label.label" default="Label" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="label" required="" value="${nodeInstance?.label}"/>
</div>

grails-app/views/node/index.gsp
<%@ page import="com.mice.Node" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'node.label', default: 'Node')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-node" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-node" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="label" title="${message(code: 'node.label.label', default: 'Label')}" />
					
						<g:sortableColumn property="data" title="${message(code: 'node.data.label', default: 'Data')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'node.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'node.lastUpdated.label', default: 'Last Updated')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${nodeInstanceList}" status="i" var="nodeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${nodeInstance.id}">${fieldValue(bean: nodeInstance, field: "label")}</g:link></td>
					
						<td>${fieldValue(bean: nodeInstance, field: "data")}</td>
					
						<td><g:formatDate date="${nodeInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${nodeInstance.lastUpdated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${nodeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/nodeChart/list.gsp
<html>
  <head>        
    <title>test</title>         

 
  </head>   
  <body>     
<g:each in="${result}">
    <tr>
        <td>${it.nodeLabel}</td>
        <td>${it.data}</td>
    </tr>
</g:each>
       
  </body> 
</html>

grails-app/views/nodeChart/test.gsp
<html>
  <head>        
    <title>test</title>         

 
  </head>   
  <body>     
<g:each in="${result}">
    <tr>
        <td>${it.nodeLabel}</td>
        <td>${it.data}</td>
    </tr>
</g:each>
       
  </body> 
</html>